#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#頁面要導入時的名稱
app_show:
    #網頁訪問路徑
    path: /show
    #對應的Controller::function名稱
    controller: App\Controller\MessageController::show
    methods: get

app_create:
    path: /create
    controller: App\Controller\MessageController::create
    methods: post

app_edit:
    path: /edit
    controller: App\Controller\MessageController::edit

app_update:
    path: /update
    controller: App\Controller\MessageController::update